#!/usr/bin/env python3
"""dashboard.py — Interactive Streamlit dashboard for the Teiknical assessment.

Displays results from Parts 2-4. Reads from the SQLite database created by
load_data.py and the output files generated by pipeline.py.
"""

import sqlite3
from pathlib import Path

import pandas as pd
import plotly.graph_objects as go
import streamlit as st
from scipy import stats
from statsmodels.stats.multitest import multipletests

DB_PATH = Path("cell_counts.db")
OUTPUT_DIR = Path("outputs")

POPULATIONS = ["b_cell", "cd8_t_cell", "cd4_t_cell", "nk_cell", "monocyte"]

POPULATION_LABELS = {
    "b_cell": "B Cell",
    "cd8_t_cell": "CD8 T Cell",
    "cd4_t_cell": "CD4 T Cell",
    "nk_cell": "NK Cell",
    "monocyte": "Monocyte",
}

# Teiko-inspired palette
C = {
    "bg": "#0F172A",
    "card": "#1E293B",
    "border": "#334155",
    "text": "#F8FAFC",
    "text2": "#94A3B8",
    "muted": "#64748B",
    "teal": "#2DD4BF",
    "coral": "#F87171",
    "blue": "#60A5FA",
    "amber": "#FBBF24",
    "violet": "#A78BFA",
}

POP_COLORS = {
    "b_cell": C["blue"],
    "cd8_t_cell": C["coral"],
    "cd4_t_cell": C["teal"],
    "nk_cell": C["amber"],
    "monocyte": C["violet"],
}


# ---------------------------------------------------------------------------
# Page config and styling
# ---------------------------------------------------------------------------

st.set_page_config(
    page_title="Cell Count Analysis",
    page_icon=None,
    layout="wide",
)

st.markdown(f"""
<style>
    .stApp {{
        background-color: {C["bg"]};
        color: {C["text"]};
    }}
    .stApp header {{
        background-color: {C["bg"]};
    }}
    section[data-testid="stSidebar"] {{
        background-color: {C["card"]};
    }}
    .metric-card {{
        background: {C["card"]};
        border: 1px solid {C["border"]};
        border-radius: 8px;
        padding: 16px 20px;
        text-align: center;
    }}
    .metric-label {{
        font-size: 11px;
        font-weight: 600;
        letter-spacing: 0.05em;
        text-transform: uppercase;
        color: {C["text2"]};
        margin-bottom: 4px;
    }}
    .metric-value {{
        font-size: 28px;
        font-weight: 700;
        color: {C["teal"]};
    }}
    .metric-value.coral {{
        color: {C["coral"]};
    }}
    .metric-value.white {{
        color: {C["text"]};
    }}
    .section-header {{
        font-size: 12px;
        font-weight: 700;
        letter-spacing: 0.08em;
        text-transform: uppercase;
        color: {C["text2"]};
        margin-top: 40px;
        margin-bottom: 4px;
    }}
    .section-title {{
        font-size: 22px;
        font-weight: 700;
        color: {C["text"]};
        margin-bottom: 20px;
    }}
    .filter-banner {{
        background: {C["card"]};
        border: 1px solid {C["border"]};
        border-radius: 6px;
        padding: 8px 16px;
        font-size: 13px;
        color: {C["text2"]};
        margin-bottom: 16px;
        display: inline-block;
    }}
    .footer {{
        font-size: 12px;
        color: {C["muted"]};
        text-align: center;
        margin-top: 60px;
        padding: 20px;
        border-top: 1px solid {C["border"]};
    }}
    div[data-testid="stDataFrame"] {{
        background-color: {C["card"]};
        border-radius: 8px;
    }}
</style>
""", unsafe_allow_html=True)


# ---------------------------------------------------------------------------
# Data loading
# ---------------------------------------------------------------------------

@st.cache_resource
def get_connection():
    return sqlite3.connect(DB_PATH, check_same_thread=False)


@st.cache_data
def load_summary():
    return pd.read_csv(OUTPUT_DIR / "summary.csv")



@st.cache_data
def load_breakdown():
    return pd.read_csv(OUTPUT_DIR / "cohort_breakdown.csv")


@st.cache_data
def load_db_metadata():
    conn = get_connection()
    samples = pd.read_sql("SELECT COUNT(*) AS n FROM samples", conn).iloc[0]["n"]
    subjects = pd.read_sql("SELECT COUNT(*) AS n FROM subjects", conn).iloc[0]["n"]
    projects = pd.read_sql("SELECT COUNT(*) AS n FROM projects", conn).iloc[0]["n"]
    return int(samples), int(subjects), int(projects)


@st.cache_data
def load_responder_cohort():
    """Load melanoma + miraclib + PBMC cohort with relative frequencies."""
    conn = get_connection()
    query = """
        SELECT sample, subject, response,
               time_from_treatment_start AS day,
               b_cell, cd8_t_cell, cd4_t_cell, nk_cell, monocyte
        FROM sample_view
        WHERE condition = 'melanoma'
          AND treatment = 'miraclib'
          AND sample_type = 'PBMC'
          AND response IS NOT NULL
    """
    df = pd.read_sql(query, conn)
    df["total_count"] = df[POPULATIONS].sum(axis=1)
    for pop in POPULATIONS:
        df[f"{pop}_pct"] = 100.0 * df[pop] / df["total_count"]
    return df


@st.cache_data
def load_filter_options():
    conn = get_connection()
    projects = [r[0] for r in conn.execute("SELECT id FROM projects ORDER BY id").fetchall()]
    conditions = [r[0] for r in conn.execute("SELECT DISTINCT condition FROM sample_view ORDER BY condition").fetchall()]
    treatments = [r[0] for r in conn.execute("SELECT DISTINCT treatment FROM sample_view ORDER BY treatment").fetchall()]
    return projects, conditions, treatments


# ---------------------------------------------------------------------------
# Components
# ---------------------------------------------------------------------------

def metric_card(label: str, value: str, color_class: str = "") -> str:
    return f"""
    <div class="metric-card">
        <div class="metric-label">{label}</div>
        <div class="metric-value {color_class}">{value}</div>
    </div>
    """


def section_header(label: str, title: str) -> None:
    st.markdown(f'<div class="section-header">{label}</div>', unsafe_allow_html=True)
    st.markdown(f'<div class="section-title">{title}</div>', unsafe_allow_html=True)


# ---------------------------------------------------------------------------
# Header
# ---------------------------------------------------------------------------

st.markdown(f"""
<div style="margin-bottom: 8px;">
    <span style="font-size: 28px; font-weight: 700; color: {C['text']};">
        Cell Count Analysis Dashboard
    </span>
</div>
<div style="color: {C['text2']}; font-size: 14px; margin-bottom: 24px;">
    Immune cell population profiling across clinical trial cohorts
</div>
""", unsafe_allow_html=True)

n_samples, n_subjects, n_projects = load_db_metadata()

cols = st.columns(4)
with cols[0]:
    st.markdown(metric_card("Total Samples", f"{n_samples:,}"), unsafe_allow_html=True)
with cols[1]:
    st.markdown(metric_card("Total Subjects", f"{n_subjects:,}"), unsafe_allow_html=True)
with cols[2]:
    st.markdown(metric_card("Projects", str(n_projects)), unsafe_allow_html=True)
with cols[3]:
    st.markdown(metric_card("Cell Populations", "5"), unsafe_allow_html=True)


# ---------------------------------------------------------------------------
# Section 1: Relative Frequency Summary
# ---------------------------------------------------------------------------

section_header("PART 2", "Relative Frequency Summary")

summary_df = load_summary()
projects_list, conditions_list, treatments_list = load_filter_options()

with st.expander("Filters", expanded=False):
    fc1, fc2, fc3, fc4, fc5 = st.columns(5)
    with fc1:
        st.markdown(f'<span style="font-size:12px;color:{C["text2"]};font-weight:600;">Project</span>',
                    unsafe_allow_html=True)
        sel_projects = [p for p in projects_list
                        if st.checkbox(p, value=True, key=f"proj_{p}")]
    with fc2:
        st.markdown(f'<span style="font-size:12px;color:{C["text2"]};font-weight:600;">Condition</span>',
                    unsafe_allow_html=True)
        sel_conditions = [c for c in conditions_list
                          if st.checkbox(c, value=True, key=f"cond_{c}")]
    with fc3:
        st.markdown(f'<span style="font-size:12px;color:{C["text2"]};font-weight:600;">Treatment</span>',
                    unsafe_allow_html=True)
        sel_treatments = [t for t in treatments_list
                          if st.checkbox(t, value=True, key=f"treat_{t}")]
    with fc4:
        st.markdown(f'<span style="font-size:12px;color:{C["text2"]};font-weight:600;">Timepoint</span>',
                    unsafe_allow_html=True)
        sel_timepoints = [tp for tp in [0, 7, 14]
                          if st.checkbox(f"Day {tp}", value=True, key=f"tp_{tp}")]
    with fc5:
        st.markdown(f'<span style="font-size:12px;color:{C["text2"]};font-weight:600;">Population</span>',
                    unsafe_allow_html=True)
        sel_populations = [pop for pop in POPULATIONS
                           if st.checkbox(POPULATION_LABELS[pop], value=True, key=f"pop_{pop}")]

# Build filtered query
conn = get_connection()
filtered_query = """
    SELECT sample
    FROM sample_view
    WHERE project IN ({proj})
      AND condition IN ({cond})
      AND treatment IN ({treat})
      AND time_from_treatment_start IN ({tp})
""".format(
    proj=",".join(f"'{p}'" for p in sel_projects) if sel_projects else "'_none_'",
    cond=",".join(f"'{c}'" for c in sel_conditions) if sel_conditions else "'_none_'",
    treat=",".join(f"'{t}'" for t in sel_treatments) if sel_treatments else "'_none_'",
    tp=",".join(str(t) for t in sel_timepoints) if sel_timepoints else "-1",
)
filtered_samples = pd.read_sql(filtered_query, conn)["sample"].tolist()
display_df = summary_df[
    summary_df["sample"].isin(filtered_samples)
    & summary_df["population"].isin(sel_populations)
].copy()

st.markdown(
    f'<span style="color: {C["text2"]}; font-size: 13px;">'
    f'Showing {display_df["sample"].nunique():,} samples, {len(display_df):,} rows</span>',
    unsafe_allow_html=True,
)

st.dataframe(
    display_df,
    use_container_width=True,
    height=400,
    column_config={
        "sample": st.column_config.TextColumn("Sample"),
        "total_count": st.column_config.NumberColumn("Total Count", format="%d"),
        "population": st.column_config.TextColumn("Population"),
        "count": st.column_config.NumberColumn("Count", format="%d"),
        "percentage": st.column_config.NumberColumn("Percentage (%)", format="%.2f"),
    },
)

csv_data = display_df.to_csv(index=False)
st.download_button(
    f"Download CSV ({display_df['sample'].nunique():,} samples, {len(display_df):,} rows)",
    data=csv_data,
    file_name="summary_filtered.csv",
    mime="text/csv",
)


# ---------------------------------------------------------------------------
# Section 2: Responder vs Non-Responder Analysis
# ---------------------------------------------------------------------------

section_header("PART 3", "Responder vs. Non-Responder Analysis")

st.markdown(
    f'<div class="filter-banner">Melanoma &bull; Miraclib &bull; PBMC</div>',
    unsafe_allow_html=True,
)

cohort_df = load_responder_cohort()

# --- Controls row ---
ctrl1, ctrl2, ctrl3 = st.columns(3)
with ctrl1:
    test_type = st.selectbox(
        "Statistical Test",
        ["Welch's t-test", "Mann-Whitney U"],
        index=0,
        key="stat_test",
    )
with ctrl2:
    timepoint_option = st.selectbox(
        "Timepoint",
        ["All (per-subject average)", "Day 0", "Day 7", "Day 14"],
        index=0,
        key="stat_tp",
    )
with ctrl3:
    fdr_threshold = st.slider(
        "FDR Threshold",
        min_value=0.01, max_value=0.20, value=0.05, step=0.01,
        key="fdr_thresh",
    )

# --- Prepare data based on timepoint selection ---
tp_map = {"Day 0": 0, "Day 7": 7, "Day 14": 14}
pct_cols = [f"{pop}_pct" for pop in POPULATIONS]

if timepoint_option in tp_map:
    # Single timepoint: one independent sample per subject
    analysis_df = cohort_df[cohort_df["day"] == tp_map[timepoint_option]].copy()
    tp_label = timepoint_option
else:
    # All timepoints: average across timepoints per subject
    analysis_df = (
        cohort_df.groupby(["subject", "response"])[pct_cols]
        .mean()
        .reset_index()
    )
    tp_label = "All timepoints (per-subject average)"

resp_vals = analysis_df[analysis_df["response"] == "yes"]
nonresp_vals = analysis_df[analysis_df["response"] == "no"]
n_resp = len(resp_vals)
n_nonresp = len(nonresp_vals)

# --- Cohort summary cards ---
cc1, cc2, cc3 = st.columns(3)
with cc1:
    unit = "subjects" if timepoint_option not in tp_map else "samples"
    st.markdown(metric_card("Responders", f"{n_resp:,}"), unsafe_allow_html=True)
with cc2:
    st.markdown(metric_card("Non-Responders", f"{n_nonresp:,}", "coral"), unsafe_allow_html=True)
with cc3:
    st.markdown(metric_card("Timepoint", tp_label, "white"), unsafe_allow_html=True)

# --- Run statistical tests across all 5 populations ---
raw_pvals = []
test_results = {}
for pop in POPULATIONS:
    col = f"{pop}_pct"
    r = resp_vals[col].dropna()
    nr = nonresp_vals[col].dropna()

    if test_type == "Mann-Whitney U":
        stat_val, pval = stats.mannwhitneyu(r, nr, alternative="two-sided")
    else:
        stat_val, pval = stats.ttest_ind(r, nr, equal_var=False)

    raw_pvals.append(pval)
    test_results[pop] = {
        "statistic": stat_val,
        "p_raw": pval,
        "resp_median": r.median(),
        "nonresp_median": nr.median(),
        "resp_mean": r.mean(),
        "nonresp_mean": nr.mean(),
    }

# BH FDR correction
_, bh_pvals, _, _ = multipletests(raw_pvals, alpha=fdr_threshold, method="fdr_bh")
for i, pop in enumerate(POPULATIONS):
    test_results[pop]["p_adj"] = bh_pvals[i]
    test_results[pop]["significant"] = bh_pvals[i] < fdr_threshold

# --- Render 5 population sub-blocks ---
for pop in POPULATIONS:
    label = POPULATION_LABELS[pop]
    res = test_results[pop]
    pct_col = f"{pop}_pct"
    pop_color = POP_COLORS[pop]

    is_sig_bh = res["significant"]
    is_sig_raw = res["p_raw"] < fdr_threshold

    if is_sig_bh:
        sig_color = C["teal"]
        sig_star = " **"
        badge_bg = C["teal"]
        badge_text = "SIGNIFICANT"
        badge_note = ""
        border_color = C["teal"]
    elif is_sig_raw:
        sig_color = C["amber"]
        sig_star = " *"
        badge_bg = C["amber"]
        badge_text = "SIGNIFICANT BEFORE CORRECTION"
        badge_note = (
            f'<div style="font-size:11px;color:{C["amber"]};margin-top:4px;">'
            f'Raw p = {res["p_raw"]:.4f} is significant, but does not survive '
            f'FDR correction (BH adj. p = {res["p_adj"]:.4f}).</div>'
        )
        border_color = C["amber"]
    else:
        sig_color = C["muted"]
        sig_star = ""
        badge_bg = C["border"]
        badge_text = "NOT SIGNIFICANT"
        badge_note = ""
        border_color = C["border"]

    # Sub-block header with significance badge
    st.markdown(
        f'<div style="display:flex;align-items:center;gap:12px;margin-top:28px;margin-bottom:4px;'
        f'padding-bottom:8px;border-bottom:2px solid {border_color};">'
        f'<span style="font-size:17px;font-weight:700;color:{C["text"]};">{label}</span>'
        f'<span style="font-size:10px;font-weight:700;letter-spacing:0.06em;'
        f'background:{badge_bg};color:{C["bg"]};padding:3px 10px;border-radius:4px;">'
        f'{badge_text}</span>'
        f'</div>'
        f'{badge_note}',
        unsafe_allow_html=True,
    )

    plot_col, stats_col = st.columns([2, 1])

    # --- Boxplot ---
    with plot_col:
        r_data = resp_vals[pct_col]
        nr_data = nonresp_vals[pct_col]
        fig = go.Figure()

        for data, name, color in [
            (r_data, "Responder", C["teal"]),
            (nr_data, "Non-Responder", C["coral"]),
        ]:
            q1 = data.quantile(0.25)
            med = data.median()
            q3 = data.quantile(0.75)
            mn, mx = data.min(), data.max()

            fig.add_trace(go.Box(
                y=data, name=name,
                marker_color=color, fillcolor=color,
                line_color=color, opacity=0.7,
                boxmean=False, hoverinfo="skip",
            ))
            fig.add_trace(go.Scatter(
                x=[name], y=[med],
                mode="markers",
                marker=dict(size=30, opacity=0),
                showlegend=False,
                hovertemplate=(
                    f"<b>{name}</b><br>"
                    f"Max: {mx:.1f}<br>"
                    f"Q3: {q3:.1f}<br>"
                    f"<span style='color:{color}'>Median: {med:.1f}</span><br>"
                    f"Q1: {q1:.1f}<br>"
                    f"Min: {mn:.1f}"
                    f"<extra></extra>"
                ),
            ))

        # Significance annotation on plot
        annotations = []
        if is_sig_raw or is_sig_bh:
            star_text = "**" if is_sig_bh else "*"
            y_max = max(r_data.max(), nr_data.max())
            annotations.append(dict(
                text=star_text,
                x=0.5, y=y_max * 1.05,
                xref="paper", yref="y",
                showarrow=False,
                font=dict(color=sig_color, size=24, family="Arial Black"),
            ))
            # Bracket line between the two boxes
            annotations.append(dict(
                text=f"p = {res['p_raw']:.4f}",
                x=0.5, y=y_max * 1.10,
                xref="paper", yref="y",
                showarrow=False,
                font=dict(color=sig_color, size=11, family="monospace"),
            ))

        fig.update_layout(
            paper_bgcolor=C["bg"],
            plot_bgcolor=C["card"],
            font=dict(color=C["text2"], size=11),
            showlegend=False,
            height=320,
            margin=dict(l=50, r=20, t=50, b=40),
            hoverlabel=dict(
                bgcolor=C["card"],
                bordercolor=C["border"],
                font=dict(color=C["text"], size=12),
            ),
            yaxis=dict(
                title="Relative Frequency (%)",
                gridcolor=C["border"],
                zerolinecolor=C["border"],
            ),
            xaxis=dict(gridcolor=C["border"]),
            annotations=annotations,
        )
        st.plotly_chart(fig, use_container_width=True)

    # --- Stats panel ---
    with stats_col:
        center_label = "Median" if test_type == "Mann-Whitney U" else "Mean"
        r_center = res["resp_median"] if test_type == "Mann-Whitney U" else res["resp_mean"]
        nr_center = res["nonresp_median"] if test_type == "Mann-Whitney U" else res["nonresp_mean"]

        st.markdown(
            f'<div style="background:{C["card"]};border:1px solid {C["border"]};'
            f'border-radius:8px;padding:16px;margin-top:4px;">'
            # Test info
            f'<div style="font-size:11px;color:{C["text2"]};font-weight:600;'
            f'letter-spacing:0.04em;text-transform:uppercase;margin-bottom:12px;">'
            f'{test_type}</div>'
            # Statistic
            f'<div style="display:flex;justify-content:space-between;margin-bottom:6px;">'
            f'<span style="color:{C["text2"]};font-size:13px;">Statistic</span>'
            f'<span style="color:{C["text"]};font-size:13px;font-weight:600;">'
            f'{res["statistic"]:.2f}</span></div>'
            # Raw p-value
            f'<div style="display:flex;justify-content:space-between;margin-bottom:6px;">'
            f'<span style="color:{C["text2"]};font-size:13px;">p-value (raw)</span>'
            f'<span style="color:{C["text"]};font-size:13px;font-family:monospace;">'
            f'{res["p_raw"]:.4f}</span></div>'
            # Adjusted p-value
            f'<div style="display:flex;justify-content:space-between;margin-bottom:12px;">'
            f'<span style="color:{C["text2"]};font-size:13px;">p-value (BH adj.)</span>'
            f'<span style="color:{sig_color};font-size:13px;font-weight:700;font-family:monospace;">'
            f'{res["p_adj"]:.4f}{sig_star}</span></div>'
            # Divider
            f'<div style="border-top:1px solid {C["border"]};margin:8px 0;"></div>'
            # Responder center
            f'<div style="display:flex;justify-content:space-between;margin-bottom:6px;">'
            f'<span style="color:{C["teal"]};font-size:13px;">Resp. {center_label}</span>'
            f'<span style="color:{C["teal"]};font-size:13px;font-weight:600;">'
            f'{r_center:.2f}%</span></div>'
            # Non-responder center
            f'<div style="display:flex;justify-content:space-between;">'
            f'<span style="color:{C["coral"]};font-size:13px;">Non-Resp. {center_label}</span>'
            f'<span style="color:{C["coral"]};font-size:13px;font-weight:600;">'
            f'{nr_center:.2f}%</span></div>'
            f'</div>',
            unsafe_allow_html=True,
        )

# --- Methodology footnote ---
st.markdown(
    f'<div style="color:{C["muted"]};font-size:11px;margin-top:16px;">'
    f'{test_type} (two-sided) with Benjamini-Hochberg FDR correction '
    f'(threshold = {fdr_threshold:.2f}). '
    f'Timepoint: {tp_label}. '
    f'n = {n_resp} responders, {n_nonresp} non-responders.</div>',
    unsafe_allow_html=True,
)


# ---------------------------------------------------------------------------
# Section 3: Cohort Breakdown
# ---------------------------------------------------------------------------

section_header("PART 4", "Cohort Breakdown")

st.markdown(
    f'<div class="filter-banner">Melanoma &bull; Miraclib &bull; PBMC &bull; Baseline (day 0)</div>',
    unsafe_allow_html=True,
)

breakdown_df = load_breakdown()

total_baseline = breakdown_df.loc[breakdown_df["metric"] == "project", "count"].sum()

st.markdown(f"""
<div style="text-align: center; margin: 20px 0;">
    <div class="metric-card" style="display: inline-block; min-width: 240px;">
        <div class="metric-label">Baseline Samples</div>
        <div class="metric-value" style="font-size: 40px;">{total_baseline}</div>
        <div style="color: {C['muted']}; font-size: 12px; margin-top: 4px;">
            Melanoma, miraclib, PBMC, day 0
        </div>
    </div>
</div>
""", unsafe_allow_html=True)

bc1, bc2, bc3 = st.columns(3)

# By Project
proj_data = breakdown_df[breakdown_df["metric"] == "project"]
with bc1:
    st.markdown(f'<div class="metric-label" style="margin-bottom: 12px;">BY PROJECT</div>',
                unsafe_allow_html=True)
    for _, row in proj_data.iterrows():
        st.markdown(
            f'<div style="display: flex; justify-content: space-between; '
            f'padding: 8px 12px; background: {C["card"]}; border: 1px solid {C["border"]}; '
            f'border-radius: 6px; margin-bottom: 6px;">'
            f'<span style="color: {C["text2"]};">{row["category"]}</span>'
            f'<span style="color: {C["text"]}; font-weight: 700;">{row["count"]}</span>'
            f'</div>',
            unsafe_allow_html=True,
        )

# By Response
resp_data = breakdown_df[breakdown_df["metric"] == "response"]
with bc2:
    st.markdown(f'<div class="metric-label" style="margin-bottom: 12px;">BY RESPONSE</div>',
                unsafe_allow_html=True)
    for _, row in resp_data.iterrows():
        is_yes = row["category"] == "yes"
        color = C["teal"] if is_yes else C["coral"]
        label = "Responders" if is_yes else "Non-Responders"
        st.markdown(
            f'<div style="display: flex; justify-content: space-between; '
            f'padding: 8px 12px; background: {C["card"]}; border-left: 3px solid {color}; '
            f'border-radius: 6px; margin-bottom: 6px;">'
            f'<span style="color: {C["text2"]};">{label}</span>'
            f'<span style="color: {color}; font-weight: 700;">{row["count"]}</span>'
            f'</div>',
            unsafe_allow_html=True,
        )

# By Sex
sex_data = breakdown_df[breakdown_df["metric"] == "sex"]
with bc3:
    st.markdown(f'<div class="metric-label" style="margin-bottom: 12px;">BY SEX</div>',
                unsafe_allow_html=True)
    for _, row in sex_data.iterrows():
        label = "Male" if row["category"] == "M" else "Female"
        st.markdown(
            f'<div style="display: flex; justify-content: space-between; '
            f'padding: 8px 12px; background: {C["card"]}; border: 1px solid {C["border"]}; '
            f'border-radius: 6px; margin-bottom: 6px;">'
            f'<span style="color: {C["text2"]};">{label}</span>'
            f'<span style="color: {C["text"]}; font-weight: 700;">{row["count"]}</span>'
            f'</div>',
            unsafe_allow_html=True,
        )


# ---------------------------------------------------------------------------
# Footer
# ---------------------------------------------------------------------------

st.markdown(f"""
<div class="footer">
    Methodology: Statistical comparisons use the Mann-Whitney U test (two-sided, alpha = 0.05).
    Relative frequencies calculated as (population count / total count) x 100 for each sample.
    Database: SQLite with normalized schema (3NF).
    <br>
    Data source: cell-count.csv &bull; {n_samples:,} samples &bull; {n_subjects:,} subjects &bull; {n_projects} projects
</div>
""", unsafe_allow_html=True)
